[env:arduino_nano_esp32]
platform = espressif32
board = arduino_nano_esp32
framework = arduino
board_microros_distro = jazzy

; Ajusta la velocidad del Monitor Serie
monitor_speed = 115200

; Activa la consola sobre el USB nativo del ESP32-S3
build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1

lib_deps =
    madhephaestus/ESP32Servo@^3.0.5
    https://github.com/micro-ROS/micro_ros_platformio