thrust_allocation_node:
  ros__parameters:
    mass: 3.0       # kg
    d1x: 0.35       # metre
    d1y: 0.35
    d2x: 0.35
    d2y: 0.35
    d3x: 0.35
    d3y: 0.35
    m1: 0           # metre
    m2: 0
    m3: 0
    deadzone: 0.05  # controller
